# Generated by Django 5.0.6 on 2024-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('Nationality', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Guardian_name', models.CharField(max_length=100)),
                ('Reationship_with_student', models.CharField(max_length=100)),
            ],
        ),
    ]
