# Generated by Django 5.0.6 on 2024-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_coach_sport_team_trainingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Contact',
            field=models.CharField(max_length=100),
        ),
    ]
