# Generated by Django 5.0.6 on 2024-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_event_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Sport',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Teams',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
