# Generated by Django 5.0.6 on 2024-06-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_students_sport_students_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Reationship_with_student',
            new_name='Relationship_with_student',
        ),
    ]
